# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: IOGesture.Test GitHub Pages

permissions:
  contents: write
  
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Add AOT Workload
      run: |
        dotnet workload install wasm-tools-net7
        dotnet workload restore
       
    - name: Restore dependencies
      run: dotnet restore ./IOGesture/IOGesture.Test/IOGesture.Test.csproj
      
    - name: Build
      run: dotnet build ./IOGesture/IOGesture.Test/IOGesture.Test.csproj --no-restore
      
    # Publishes Blazor project to the release folder
    - name: Publish Blazor
      run: dotnet publish ./IOGesture/IOGesture.Test/IOGesture.Test.csproj -c Release -o release --nologo
      
    - name: Change base-tag in index.html from / to /IOGesture/IOGesture.Test/
      run: sed -i 's|<base href="/" />|<base href="/IOGesture/IOGesture.Test/" />|g' release/wwwroot/index.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        BRANCH: gh-pages
        FOLDER: release/wwwroot
